services:
  - type: worker
    name: sahukgs-tg-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_ID
        value: ""
      - key: BATCH_URL
        value: https://www.sahukgs.com/batch/1159
      - key: SEND_VIDEO
        value: "true"
